"""init

Revision ID: 59ecca971a57
Revises: 
Create Date: 2026-04-06 17:48:12.848263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ecca971a57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_label', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("file_type IN ('text', 'image', 'video')", name='ck_analyses_file_type'),
    sa.CheckConstraint("model_type IN ('text', 'image', 'video', 'multimodal')", name='ck_analyses_model_type'),
    sa.CheckConstraint("result_label IN ('REAL', 'FAKE')", name='ck_analyses_result_label'),
    sa.CheckConstraint("status IN ('processing', 'success', 'failed')", name='ck_analyses_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_analyses_confidence'),
    sa.CheckConstraint('file_size >= 0', name='ck_analyses_file_size'),
    sa.CheckConstraint('inference_time_ms >= 0', name='ck_analyses_inference_time_ms'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_file_type'), 'analyses', ['file_type'], unique=False)
    op.create_index(op.f('ix_analyses_model_type'), 'analyses', ['model_type'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('analysis_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_logs_analysis_id'), 'analysis_logs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_logs_created_at'), 'analysis_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_logs_created_at'), table_name='analysis_logs')
    op.drop_index(op.f('ix_analysis_logs_analysis_id'), table_name='analysis_logs')
    op.drop_table('analysis_logs')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_model_type'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_file_type'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
